### ISSUE TITLE
Client ID not found

### ISSUE THREAD

**Issue by Mick2011** [roleoroleo/yi-hack-Allwinner.gdrive#1]
Hi, thank you so much for creating this hack. It's just what I've been waiting for and can almost follow the instructions! Just one point I am getting stuck on. I have created a Project and associated credentials and secret but when I run the command sh /tmp/sd/yi-hack/gdrive/GDriveConf it tells me to wait a few seconds. I do this and then enter in the client ID but instantly it returns the message "not found"

Any ideas where I may be going wrong? I am copying and pasting the client ID so no risk of error there.

**Comment by Mick2011** [comment]
> Did you try the script?

Tried it again starting from scratch but still facing the same issue. Any ideas? Anybody else have it working?

**Comment by roleoroleo** [comment]
Tomorrow, I will try again on my cam.

**Comment by roleoroleo** [comment]
I tested it and it works.

**Comment by Mick2011** [comment]
Not sure what I am doing wrong so or need to change. If anyone else tries
it be sure and let us know how it goes.

**Comment by roleoroleo** [comment]
Try to source the env file before GDriveConf command:
`. /home/yi-hack/script/env.sh`

**Comment by Mick2011** [comment]
> Try to source the env file before GDriveConf command:
> `. /home/yi-hack/script/env.sh`

It finds the file but still getting "not found" message.

**Comment by roleoroleo** [comment]
Check if you have the same problem:
https://github.com/roleoroleo/yi-hack-Allwinner/issues/132#issuecomment-682008019

**Comment by Mick2011** [comment]
> Check if you have the same problem:
> [roleoroleo/yi-hack-Allwinner#132 (comment)](https://github.com/roleoroleo/yi-hack-Allwinner/issues/132#issuecomment-682008019)

To the untrained eye it looks ok to me.
![configsh](https://user-images.githubusercontent.com/4801480/91554887-e13ba400-e927-11ea-8a22-20c43a13ef9a.png)

**Comment by roleoroleo** [comment]
Sorry, I mean in the file GDriveConf.
And the other files in the same path.

**Comment by Mick2011** [comment]
Checked all files and all lines end in LF in all the files. A bit of a mystery this one.

**Comment by Mick2011** [comment]
Finally got it working. Not sure what it was but I re-downloaded and copied the files over for a third time and then it worked. Thanks for your help.

**Comment by roleoroleo** [comment]
This is my last commit:
https://github.com/roleoroleo/yi-hack-Allwinner.gdrive/commit/9ca08307f6a877454cc6d804efa2533c6bba97c2
